services:
  - type: web
    name: password-generator
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      mkdir -p backend/static
      cp -r frontend/static/* backend/static/
      mkdir -p backend/lang
      cp -r frontend/lang/* backend/lang/
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PORT
        value: 10000
    staticDirs:
      - path: /static
        directory: frontend/static
      - path: /lang
        directory: frontend/lang
      - path: /assets
        directory: frontend/assets